INSERT INTO CURRICULUM (C_ID, CREATOR, DATE_CREATED, IS_MASTER, MODIFIER, NAME, NUMBER_OF_WEEKS, VERSION) VALUES (8, 50, '03/21/2018', 1, NULL, 'C++', 0, 1);
 
INSERT INTO CURRICULUM (C_ID, CREATOR, DATE_CREATED, IS_MASTER, MODIFIER, NAME, NUMBER_OF_WEEKS, VERSION) VALUES (21, 50, '03/22/2018', 1, NULL, 'C#', 0, 1);
 
INSERT INTO CURRICULUM (C_ID, CREATOR, DATE_CREATED, IS_MASTER, MODIFIER, NAME, NUMBER_OF_WEEKS, VERSION) VALUES (22, 50, '03/22/2018', 2, NULL, 'C#', 0, 2);
 
INSERT INTO CURRICULUM (C_ID, CREATOR, DATE_CREATED, IS_MASTER, MODIFIER, NAME, NUMBER_OF_WEEKS, VERSION) VALUES (23, 50, '03/22/2018', 1, NULL, 'Java2', 0, 1);

INSERT INTO CURRICULUM (C_ID, CREATOR, DATE_CREATED, IS_MASTER, MODIFIER, NAME, NUMBER_OF_WEEKS, VERSION) VALUES (1, 50, '03/22/2018', 0, NULL, 'Java', 13, 1);


INSERT INTO CURRICULUM_SUBTOPIC (CURRICULUM_SUBTOPIC_ID, CURRICULUM_DAY, CURRICULUM_SUBTOPIC_NAME_ID, CURRICULUM_WEEK, CURRICULUM_SUBTOPIC_CUR_ID) VALUES (1, 1, 1, 1, 1);