INSERT INTO CURRICULUM (ID, CREATOR_ID, DATE_CREATED, MASTER_VERSION, MODIFIER_ID, NAME, WEEK_DURATION, VERSION) VALUES (8, 50, TO_TIMESTAMP('02/MAY/2018 12:00:00'), true, 0, 'C++', 0, 1);
 
INSERT INTO CURRICULUM (ID, CREATOR_ID, DATE_CREATED, MASTER_VERSION, MODIFIER_ID, NAME, WEEK_DURATION, VERSION) VALUES (21, 50, TO_TIMESTAMP('02/MAY/2018 12:00:00'), true, 0, 'C#', 0, 1);
 
INSERT INTO CURRICULUM (ID, CREATOR_ID, DATE_CREATED, MASTER_VERSION, MODIFIER_ID, NAME, WEEK_DURATION, VERSION) VALUES (22, 50, TO_TIMESTAMP('02/MAY/2018 12:00:00'), true, 0, 'C#', 0, 2);
 
INSERT INTO CURRICULUM (ID, CREATOR_ID, DATE_CREATED, MASTER_VERSION, MODIFIER_ID, NAME, WEEK_DURATION, VERSION) VALUES (23, 50, TO_TIMESTAMP('02/MAY/2018 12:00:00'), true, 0, 'Java2', 0, 1);

INSERT INTO CURRICULUM (ID, CREATOR_ID, DATE_CREATED, MASTER_VERSION, MODIFIER_ID, NAME, WEEK_DURATION, VERSION) VALUES (1, 50, TO_TIMESTAMP('02/MAY/2018 12:00:00'), false, 0, 'Java', 13, 1);

